### ISSUE TITLE
New Python release

### ISSUE THREAD

**Issue by hugovk** [dariusk/wordfilter#36]
Hi @fitnr,

The latest release on [PyPI](https://pypi.python.org/pypi/wordfilter
) (and the one you get from `pip install wordfilter`) is 0.2.5.

The Python source hasn't changed, but badwords.json has and it's at 0.2.6.

Please could you make a new Python release? I think it probably makes sense to merge [your setup.py](https://github.com/fitnr/wordfilter/blob/master/setup.py) into this repo too.

Thanks!

**Comment by fitnr** [comment]
I've backfilled the current version of `badwords.json` and uploaded a new version (`0.2.6`) to PyPi.

Feel free to grab the code from my repo if things have changed. Note that the code in my repo and on PyPi uses Python conventions (`add_words`) rather than the Javascript conventions used in the Python in this repo (`addWords`).

**Comment by hugovk** [comment]
Thanks!

I might PR your changes into here at some point, it makes sense to have the same `add_words` contention as the pip one.
